<?php


/**
 * Implements hook_permission().
 */
function helloworld_permission() {
  return array(
    'access helloworld content' => array(
      'title' => t('Access content for the Hello World module'),
    )
  );
}


/**
 * Implements hook_block_info().
 */
function helloworld_block_info() {
  $blocks = array();
  $blocks['helloworld_blk'] = array(
    // Name of the block.
    'info' => t('helloworld'),
    'region' => 'content',
    // Default setting.
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}


/**
 *Implements hook_block_view()
 */
function helloworld_block_view($delta) {
     $block = array();
     
     if ($delta == 'helloworld_blk') {
        $block['subject'] = t('Hello World!');
        $node = menu_get_object();
        // Query to get all hello world articles that have section set and enabled.
        $query = db_select('node', 'n');
        $query->join('field_data_field_sections', 'sec', 'sec.entity_id = n.nid');
        $query->join('field_data_field_enabled', 'en', 'en.entity_id = sec.field_sections_tid');
        $query->fields('n')
                   ->condition('n.type', 'hello_world_article','=')
                   ->condition('sec.bundle', 'hello_world_article','=')
                   ->condition('en.field_enabled_value', 1,'=');
        if (isset($node)) {
          $query->condition('n.nid', $node->nid, '!=');
        }
        $result = $query->execute();
     
        // Array to contain items for the block to render.
        $items = array();
        // Iterate over the result set and create links.
        foreach ($result as $node) {
          
          $items[] = array(
            'data' => l($node->title, 'node/' . $node->nid),
          );
        }
        if (empty($items)) {
          $block['content'] = t('No articles available.');  
        }
        else {
          //Pass data through the theme function
          
          $output =  array(
              '#items' => $items ,
              '#theme' => 'item_list',
    
          );
          $block['content'] = $output;
          
        }
        
      }
     

      return $block;
}

 
